In [1]:
- [Open with Colab](https://colab.research.google.com/github/GITHUB_ID/REPO_NAME/blob/master/NOTEBOOK.ipynb)

SyntaxError: invalid syntax (<ipython-input-1-339807d87fbb>, line 1)

# Numpy入門

In [2]:
# numpyをインポートして名前をnpにする．numpyのメソッドは，np.***で使える．
import numpy as np

In [3]:
# 行列
A = np.array([[1,2,3],[4,5,6],[7,8,9]])
A

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [4]:
# ベクトル
x = np.array([[1],[2],[3]])
print(x)

[[1]
 [2]
 [3]]


In [5]:
# 行列とベクトルの演算
b = np.dot(A, x)
print(b)

[[14]
 [32]
 [50]]


In [6]:
# こちらは違う
A * x

array([[ 1,  2,  3],
       [ 8, 10, 12],
       [21, 24, 27]])

In [7]:
# わかりやすく実行すると
A= np.array([[1,2,3],[4,5,6],[7,8,9]])
x = np.array([[10],[100],[1000]])
A * x

array([[  10,   20,   30],
       [ 400,  500,  600],
       [7000, 8000, 9000]])

In [8]:
#  定数倍
A * 2

array([[ 2,  4,  6],
       [ 8, 10, 12],
       [14, 16, 18]])